development:
  adapter: postgresql
  encoding: utf8
  database: ciderspot_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: ciderspot_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: ciderspot_production
  pool: 5
  username:
  password:
